### ISSUE TITLE
Explosion.zone certificate expired.

### ISSUE THREAD

**Issue by Kezxo** [thejamesm/Giant-Bomb-redirects#10]
Problematic!

**Comment by thejamesm** [comment]
Should be sorted now. Thanks for the heads-up.

**Comment by Kezxo** [comment]
@thejamesm it happened again!

**Comment by thejamesm** [comment]
Embarrassingly, I was getting notification emails about expiration coming up, but I'd always notice them at the least convenient times, and forget about it by the time I had a moment to fix it. Anyway, thanks for the prod.
