### ISSUE TITLE
explosion.zone uses an invalid security certificate

### ISSUE THREAD

**Issue by Kezxo** [thejamesm/Giant-Bomb-redirects#5]
> explosion.zone uses an invalid security certificate. The certificate expired on Friday, November 16, 2018, 11:21:05 PM. The current time is November 19, 2018, 3:40 AM.

**Comment by thejamesm** [comment]
Oops, fixed. getssl is meant to automatically take care of Let's Encrypt renewals, but the version of cPanel my crappy shared hosting uses doesn't seem to want to play along.
